### ISSUE TITLE
Enable page access through adress bar / refresh

### ISSUE THREAD

**Issue by nicolasdelfino** [faceyspacey/redux-first-router-demo#1]
Navigating to a sub route e.g videos/video1 and then refreshing the page gives you a 
"cannot get (whatever url you were on)"

Expected behaviour would be a page refresh

**Comment by faceyspacey** [comment]
That's just webpack-dev-server. I typically don't use that anymore for my own apps. It was generated by Webpack bin. 

Is there a way to make it catch any URL? There may be.

In the upcoming SSR article, I'll release a lower level demo using express that won't have this problem.

**Comment by nicolasdelfino** [comment]
(Facepalmed) should have thought about that, feeling like a total douche for adding it. At least now no one else will 😊
Anyway made a simplified cra demo based on yours cause and indeed - it all works as it should 
https://github.com/nicolasdelfino/rfr-simple

Cheers
