### ISSUE TITLE
Question: code splitting for reducers

### ISSUE THREAD

**Issue by marc-rutkowski** [faceyspacey/redux-first-router-demo#11]
Hi James! / @faceyspacey 

First of all I want to thank you for all the amazing work you do and share. This is very inspiring.

And there is my question:

It seems that all reducers (and action creators) [are imported](https://github.com/faceyspacey/redux-first-router-demo/blob/master/src/configureStore.js#L7) into this demo code for redux-first-router.
But it could probably be possible to split reducers code by route, isn't it?

Maybe something similar to the [asyncInjectors](https://github.com/react-boilerplate/react-boilerplate/blob/master/app/utils/asyncInjectors.js) of react-boilerplate can do the trick but I'm not sure how to integrate this within your code.
What do you think about this?

Best regards,

Marc

**Comment by faceyspacey** [comment]
Thanks brother.

I'm adding a feature to inject routes this and next week along with others in a big push. I think there may be another issue here about it to check out for info.

But consider it done. Hopefully it will get to you before your deadline.

**Comment by marc-rutkowski** [comment]
Thanks for the quick answer!
I'll be very happy to test the next version and I don't have a strong deadline for this, so don't worry :)

This is just something that I noticed while exploring and experimenting with your code.
Everything else looks very well designed and organized and I have to say it's already a pretty impressive boilerplate/starter code base!

My only small concerns at this point will be that as a user of the previously referenced react-boilerplate, I prefer the root separation of code by modules/routes instead of by types (actions, reducers, components...). But it's something that I can implements by myself into my own project and I understand that the code is more a demo of RFR/Rudy than a fully featured starter kit.

I think we can close this issue?

**Comment by faceyspacey** [comment]
Go for it brother. I actually don't understand what you would like different than what's planned. Please explain

**Comment by marc-rutkowski** [comment]
My point is just that I prefer dealing with co-located portions of all code types (actions, reducers, components) into a distinct folder for **each route** (main container) for example like this [HomePage](https://github.com/react-boilerplate/react-boilerplate/tree/master/app/containers/HomePage) component

vs 

having all reducers for all routes into the same "reducers" folder, and all action creators into another one, and so on...

But I assume it is just a matter of personal preference, right?

**Comment by faceyspacey** [comment]
Yea it shouldn't be a problem

**Comment by aga5tya** [comment]
@faceyspacey, can this be achieved in the present release? SSR needs all the sync data rendering reducers to be available if i'm not wrong ?

**Comment by faceyspacey** [comment]
OnLoad will run on the server. Give it a try and let me know how it goes.

Universal component doesn't need to be in the @next dist tag. Only RFR does.

**Comment by faceyspacey** [comment]
features to inject routes (for code-splitting) have been in the latest versions of RFR for a few weeks now. Make sure to check the updates at the top of the main RFR router.
