### ISSUE TITLE
Data-fetching via thunk or alternative (ala Next.js?)

### ISSUE THREAD

**Issue by Grsmto** [faceyspacey/redux-first-router-demo#13]
Heyyo @faceyspacey !

First, your work is really impressive! 

I was wondering by checking this repo example and the  redux-first-router doc, to do data-fetching, am I suppose to use the `thunk` property at the route level?
If I understand well, the equivalent in Next.js is `getInitialProps` which is at component level.
Is there an alternative to have things at component level with your workflow?
Would it be possible to get a GraphQL implementation this way (for example with Apollo)?

Thanks!

**Comment by faceyspacey** [comment]
Glad you like it, sorry for taking so long to respond. I haven't been checking the issues on the repo as much. 

...The whole approach is based on the route level. I love Apollo + GraphQL and plan to create a route-level approach eventually. Basically, it's my opinion that the whole *component level* thing is very bad for business and has been a mistake for the React community :). 

I've covered it at length in my places, but basically nobody really needs it besides very large companies with many developers. If you can touch the route, you should put all your data-fetching things there. Just think about it--SSR requires it to be done in the most performant way. There just hasn't been good route level abstractions until now.

Perhaps most importantly, when you separate your data-fetching dependencies from your components, it becomes far easier to test those components *(and test the data-fetching independently).*

I can list a great number of issues, but basically once data-fetching lives in components, the state they use to make the decisions of what to get starts to live in the view layer. You should be able to produce all the necessary state to generate those params based on the route and do it all in one place. There's so little value in being able to specify how the data-fetching is done along with the props mapped from result fetched state (e.g. via react-redux's `connect`). If it's with Apollo, it's better, but ad-hoc solutions end with all sorts of noise and potential problems with having to perform fetches in lifecycle handlers. You can end up over-fetching or missing fetches you make, etc. 

If you think about it, we basically live in a mobile-only world, and therefore there isn't even enough screen space to simultaneously show that much data. Do it at the route level.

I don't expect people committed to component-level to get it. But once we bring Apollo to the route level, seeing it should help. Either way, just think that if you do it at the component level, and you have multiple fetches per render, then if you're doing SSR, they can't happen in parallel. AND, if you have one fetch, you're better off formalizing it at the route-level. If you're doing RN, it makes more sense--but again, screen space is so small, it barely matters. Formalize the contract and do it at the route level :)

Now that all said, RFR is just redux. So you're free to do it at the component level all you want. Use redux to render certain components for given routes (similar to the `Switcher` component in this demo), and then add data fetching to `componentDidMount` of those components. You're now losing the SSR benefits of how easy RFR makes it to figure out which data fetching to do, but it will nicely pair with Apollo. Then Apollo has its SSR recursive component tree walking promise solution. As long as you don't have nested data-fetching, you'll end up with one fetch per route, and all will be fine in the world. You can use Apollo's SSR functions easily with RFR. It all just works.
