### ISSUE TITLE
Missing [hash] for vendor.js

### ISSUE THREAD

**Issue by chapati23** [faceyspacey/redux-first-router-demo#14]
Is there a specific reason you don't append a hash to the `vendor.js`? Can't this lead to cache invalidation issues?
⬇️ https://github.com/faceyspacey/redux-first-router-demo/blob/93fabd794b4fe8d599a600e67c092e3334758092/webpack/client.prod.js#L77

All the other outputs do have a hash, e.g.
• https://github.com/faceyspacey/redux-first-router-demo/blob/master/webpack/client.prod.js#L17-L18
• https://github.com/faceyspacey/redux-first-router-demo/blob/master/webpack/client.prod.js#L36
• https://github.com/faceyspacey/redux-first-router-demo/blob/master/webpack/client.prod.js#L51

**Comment by faceyspacey** [comment]
It's a mistake. I'm pretty sure autodll only speeds up rebuilds on HMR and is there only meant to exist in development. ...but if not, yea there should be hash.
