### ISSUE TITLE
installing on windows troubles

### ISSUE THREAD

**Issue by DavOnGit** [faceyspacey/redux-first-router-demo#17]
`yarn install` logs:

> **[2/4] Fetching packages...**
> warning fsevents@1.1.1: The platform "win32" is incompatible with this module.
> info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
> **[3/4] Linking dependencies...**
> warning "stats-webpack-plugin@0.5.0" has incorrect peer dependency "webpack@^1.0||^2.1.0-beta||^2.2.0-rc".
> warning "travis-github-status@1.4.0" has unmet peer dependency "flow-bin@*".
> warning "travis-github-status@1.4.0" has unmet peer dependency "jest@*".

What i'm missing?

**Comment by faceyspacey** [comment]
i just pushed a few sconds ago a fix for the jest/flow-bin warnings. 

The stats plugin is waiting for this PR to be merged:
https://github.com/unindented/stats-webpack-plugin/pull/24

And the fsevents one ive been getting lately on OSX as well. Some package is importing it, and apparently it's not up to date, but there's very little I can do about it. It's just a warning--it should still be working for you right?

**Comment by DavOnGit** [comment]
Not working! It hangs indefinitely (not pulled jest/flow fix yet)....
`yarn start` logs:

> ...
> rimraf buildClient buildServer
> (node:229168) Warning: .then() only accepts functions but was passed: [object Undefined]
> ...
> webpack: Compiled successfully.
> REQUESTED PATH: /sockjs/info
> CHUNK NAMES [ 'NotFound' ]
> REQUESTED PATH: /sockjs/info
> CHUNK NAMES [ 'NotFound' ]
> REQUESTED PATH: /sockjs/info
> CHUNK NAMES [ 'NotFound' ]
> REQUESTED PATH: /sockjs/info
> CHUNK NAMES [ 'NotFound' ]
> ....

**Comment by faceyspacey** [comment]
something on your computer is trying to access /socksjs/info ..that may be some other app on ur computer still running/polling. 

but in general, the app is running if you're seeing those logs.

**Comment by DavOnGit** [comment]
Yes it works, thanks :+1: 
Great job bro, keep it going :)

**Comment by faceyspacey** [comment]
np

**Comment by faceyspacey** [comment]
a new boilerplate just came out today. linked from the top of the redux-first-router homepage fyi. ..it's an easier place to start as it does far less.

https://github.com/faceyspacey/redux-first-router-boilerplate

just fyi
