### ISSUE TITLE
Question about CSS in server builds

### ISSUE THREAD

**Issue by jo12bar** [faceyspacey/redux-first-router-demo#19]
Quick question: Is there any particular reason why we're excluding CSS from `/node_modules/` in the server bundles? It breaks things like importing `normalize.css` from its npm package, and everything seems to work fine when you include it. I've linked the relevant lines below:

https://github.com/faceyspacey/redux-first-router-demo/blob/bc65d9bec8b048ccc4dc52e354b1bcc19db98302/webpack/server.dev.js#L44-54

https://github.com/faceyspacey/redux-first-router-demo/blob/bc65d9bec8b048ccc4dc52e354b1bcc19db98302/webpack/server.prod.js#L42-52

**Comment by faceyspacey** [comment]
just minor perf, since it's not used. feel free to go without it

**Comment by jo12bar** [comment]
Sweet! Thanks for the quick reply!
