### ISSUE TITLE
add publicPath to server.prod webpack config also

### ISSUE THREAD

**Issue by cahva** [faceyspacey/redux-first-router-demo#25]
https://github.com/faceyspacey/redux-first-router-demo/blob/3b1adee9ccfc8a102ae8fdb01e61c0f373455253/webpack/server.prod.js#L30-L34

I know this works in this demo but if you take this as a basis for your own project and add loaders for images, fonts etc., they are not included right on the server render as client fetches assets from /static/ and production fetches from the root. Lots of 404's and client will have to render the page again.

So I suggest adding `publicPath: '/static/'` also to the server.prod.

I have to admit that I'm a n00b with webpack and it took me a while to find the cause of this :)

**Comment by faceyspacey** [comment]
PR it, and make sure it works, and I'll accept it.

**Comment by cahva** [comment]
Okay thanks. I was not sure about it but I tested it and it works. I'm still not sure why css files get mapped correctly to static/ in the rendered html but images do not.
