### ISSUE TITLE
buildServer Files

### ISSUE THREAD

**Issue by dandigangi** [faceyspacey/redux-first-router-demo#29]
Is there a reason why the buildServer files aren't available for this demo?

It seems pertinent to understanding how you configured SSR to run on the Node side.

Thoughts?

**Comment by faceyspacey** [comment]
I'm not sure what you mean. Once you build it on your computer they will be generated.

**Comment by dandigangi** [comment]
Apologies! I misunderstood your prod server. I realize now it was just using the static JS file at `/buildServer/` now
