### ISSUE TITLE
Need a pathless example

### ISSUE THREAD

**Issue by intrepion** [faceyspacey/redux-first-router-demo#33]
Could you add an implementation of a pathless route like in this gist?

https://gist.github.com/faceyspacey/2771c05a62a338fa6d3d23d76e6e7c5a

It doesn't seem to work when I try it myself.

**Comment by faceyspacey** [comment]
The next version of RFR (which will be called Rudy) is almost out and will have better examples of this.

For now make sure you're using the @rudy tag on npm.
