### ISSUE TITLE
Errors in Redux-First Router Demo on Codesandbox

### ISSUE THREAD

**Issue by ianseverance** [faceyspacey/redux-first-router-demo#35]
To start, kick ass projects 🔥 The second I saw all of what you were building, I dropped Next.js 👍

I came back to look at one of the demos on Codesandbox, and it looks like it is throwing some errors. Not sure what changed since I last saw it. The sandbox I was viewing is the one linked in the [redux-first-router-demo README](https://codesandbox.io/s/github/faceyspacey/redux-first-router-codesandbox).

Can you confirm this?

![image](https://user-images.githubusercontent.com/16518898/34897970-f5139b54-f7ad-11e7-98db-70ec19dc6abd.png)

**Comment by faceyspacey** [comment]
glad u dropped Next.js. That's the "correct" response :)

Rudy (what RFR is being renamed to) is almost out. it's a huge deal :)

I'll revisit the codesandbox prior to launch, rest assured.

**Comment by ianseverance** [comment]
Looks like the error is cleared up. May have been an issue on Codesandbox's side (maybe https://github.com/CompuIves/codesandbox-client/commit/c9db03a862e8063700705687dc0a82b08953ac94 but who knows 🤷‍♂️)

I'm excited to see what is in store (pun semi-intended). Following these projects closely 🙌
