### ISSUE TITLE
[question] Hydrate vs Render

### ISSUE THREAD

**Issue by smeijer** [faceyspacey/redux-first-router-demo#38]
I see that you're using `ReactDOM.render` in the `rudy` branch, while you're using `ReactDOM.hydrate` in `master`. Is there a specific reason to not use `hydrate` in `rudy`?

https://github.com/faceyspacey/redux-first-router-demo/blob/rudy/src/index.js#L15

**Comment by faceyspacey** [comment]
no, it can be used.

**Comment by smeijer** [comment]
Thanks :)
