### ISSUE TITLE
Unable to get it working with jest or enzyme

### ISSUE THREAD

**Issue by ScriptedAlchemy** [faceyspacey/redux-first-router-demo#46]
Can you please provide an example of how to write unit tests on a component which renders other universal components inside it. 

I get this error
``` 
TypeError: /Volumes/fiverr_dev/careers_page_perseus/src/common/components/componentLoader.js: Property value expected type of string but got null
```

**Comment by faceyspacey** [comment]
Check the tests for React universal component or mock it. Or follow the docs for using RUC server side with babel instead of webpack. Most the docs are for webpack in both places. The docs are in the webpack flush chunks repo.

**Comment by ScriptedAlchemy** [comment]
Thanks Dude! Worked like a charm! much love
