### ISSUE TITLE
Hot Reloading Not Auto-Reloading

### ISSUE THREAD

**Issue by Maushundb** [faceyspacey/redux-first-router-demo#7]
Hey! Awesome repo. Just downloaded and started it up. It seems that you don't get true hot reloading in dev mode when you run `npm run start`. I'll make an edit to my markup, hit save, then wait for HMR to reload, and the old markup is still there. I think this may have something to do with SSR.

Is there some way to disable SSR in dev mode and enable hot reloading on save, without having to refresh the page?

**Comment by faceyspacey** [comment]
There's better than CRA style hot-reload: true HMR. If the the page isn't updating, something's wrong. 

If you're talking about changing the HTML string in `server/render.js`, sure, but that's rarely edited.

**Comment by faceyspacey** [comment]
Also, the point isn't to disable SSR in dev mode. It's to be a full HMR with SSR experience, e.g. so you experience no flashes of white if the styles existed only in the js while the js is loading yet the html was rendered.

**Comment by Maushundb** [comment]
Thanks for the quick response. Nah I'n talking about the markup in Home.js

```
<h1>HOME</h1>
```
When I change the text to whatever, then save the file, I see
```
[HMR] bundle rebuilding...
...
[HMR] App is up to date.
```

Yet the text doesn't actually change to what I change it to. It DOES however change once I fire another action by clicking on one of the sidebar items, then returning back. This is on a fresh checkout of the repo on Chrome 59

**Comment by faceyspacey** [comment]
Ok. i'll git clone it real soon and see whatsup. The demo doesn't have tests and I might have hastily broke something.

**Comment by faceyspacey** [comment]
ok, it's fixed and updated. the issue was the autdll package didn't like that i was putting react-hot-loader in there.

styles are also updated to match the CodeSandBox and a few other little tweaks. Let me know how it goes.
