### ISSUE TITLE
ESLint linebreak-style errors on Windows

### ISSUE THREAD

**Issue by corydeppen** [faceyspacey/redux-first-router-demo#8]
Given the current ESLint rules, Windows users will get a bunch of linebreak-style errors. Would you consider a PR similar to what I proposed in pburtchaell/react-notification#127?

**Comment by faceyspacey** [comment]
Yea lets do it--as long as it doesn't introduce new issues.

**Comment by faceyspacey** [comment]
FYI, i just updated the repo, so make sure u pull it in.

**Comment by corydeppen** [comment]
I believe this was resolved by #9.
